- hosts: grafana
  tasks:
    # - name: install requirements for postgres
    #   become: true
    #   apt:
    #     name:
    #       - postgresql
    #       - postgresql-contrib
    #       - python3-psycopg2
    #       - acl
    #     update_cache: true
    
    # - name: create database
    #   become: true
    #   become_user: postgres
    #   postgresql_db:
    #     state: present
    #     name: "{{ grafana_database.name }}"

    # - name: create db user
    #   become: true
    #   become_user: postgres
    #   postgresql_user:
    #     state: present
    #     name: "{{ grafana_database.user }}"
    #     password: "{{ grafana_database.password }}"
    #     role_attr_flags: CREATEDB

    # - name: grant db user access to garafana db
    #   become: true
    #   become_user: postgres
    #   postgresql_privs:
    #     type: database
    #     database: "{{ grafana_database.name }}"
    #     roles: "{{ grafana_database.user }}"
    #     grant_option: no
    #     privs: all

    - name: install grafana
      import_role:
        name: grafana.grafana.grafana
